name: 'build-images'
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: '9fans/plan9port'
        path: plan9
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev xserver-xorg-dev
        cd plan9 && ./INSTALL -b
    - name: Archive
      run: |
        tar -zcf "plan9port-$OS.tgz" --exclude='.git*' plan9
      env:
        OS: ${{ matrix.os }}
    - uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      id: auth
    - uses: google-github-actions/upload-cloud-storage@386ab77f37fdf51c0e38b3d229fad286861cc0d0 # v2.2.1
      with:
        path: plan9port-${{ matrix.os }}.tgz
        destination: setup-plan9port
