name: 'build-images'
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: '9fans/plan9port'
        path: plan9
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install xorg-dev xserver-xorg-dev
        cd plan9 && ./INSTALL -b
    - name: Archive
      run: |
        tar -zcf "plan9port-$OS.tgz" --exclude='.git*' plan9
      env:
        OS: ${{ matrix.os }}
    - uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      id: auth
    - uses: google-github-actions/upload-cloud-storage@7c73f5d6eae167341002e9c946f7479a609c588e # v2.2.3
      with:
        path: plan9port-${{ matrix.os }}.tgz
        destination: setup-plan9port
