name: 'build-images'
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: '9fans/plan9port'
        path: plan9
    - name: Build
      run: |
        cd plan9 && ./INSTALL -b
    - name: Archive
      run: |
        tar -zcf "plan9port-${{ matrix.os }}.tgz" --exclude='.git*' --exclude='.travis.yml' plan9
    - uses: google-github-actions/upload-cloud-storage@main
      with:
        path: plan9port-${{ matrix.os }}.tgz
        destination: setup-plan9port
        credentials: ${{ secrets.GCP_CREDENTIAL }}
