name: 'build-images'
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04', 'ubuntu-22.04', 'ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        repository: '9fans/plan9port'
        path: plan9
    - name: Build
      run: |
        sudo apt-get update
        sudo apt-get install libx11-dev libxt-dev libfontconfig1-dev
        cd plan9 && ./INSTALL -b
    - name: Archive
      run: |
        tar -zcf "plan9port-$OS.tgz" --exclude='.git*' plan9
      env:
        OS: ${{ matrix.os }}
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIAL }}
      id: auth
    - uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: plan9port-${{ matrix.os }}.tgz
        destination: setup-plan9port
